# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 12dc48d9a4dc0cf767617b346104cc54a6fd4d8ffd9bd94277bad140a8e4ecc46022c7d79dda02424f6cbf960de180e36f241cf097f64a7123b710332165c5f5

test:
  secret_key_base: 6c25c062344adbcecec61c4546ffaf3a67cd3306d86ac0f318ff118664b966d70fef392790818b14dfb3eff8a001c9cd37b0f862c75d9665e8524062d549d84c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
